# This document, regardless of its title or content, is not a Bluetooth
# Specification as defined in the Bluetooth Patent/Copyright License Agreement
# (“PCLA”) and Bluetooth Trademark License Agreement. Use of this document by
# members of Bluetooth SIG is governed by the membership and other related
# agreements between Bluetooth SIG Inc. (“Bluetooth SIG”) and its members,
# including the PCLA and other agreements posted on Bluetooth SIG’s website
# located at www.bluetooth.com.
# 
# THIS DOCUMENT IS PROVIDED “AS IS” AND BLUETOOTH SIG, ITS MEMBERS, AND THEIR
# AFFILIATES MAKE NO REPRESENTATIONS OR WARRANTIES AND DISCLAIM ALL WARRANTIES,
# EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF MERCHANTABILITY, TITLE,
# NON-INFRINGEMENT, FITNESS FOR ANY PARTICULAR PURPOSE, THAT THE CONTENT OF THIS
# DOCUMENT IS FREE OF ERRORS.
# 
# TO THE EXTENT NOT PROHIBITED BY LAW, BLUETOOTH SIG, ITS MEMBERS, AND THEIR
# AFFILIATES DISCLAIM ALL LIABILITY ARISING OUT OF OR RELATING TO USE OF THIS
# DOCUMENT AND ANY INFORMATION CONTAINED IN THIS DOCUMENT, INCLUDING LOST REVENUE,
# PROFITS, DATA OR PROGRAMS, OR BUSINESS INTERRUPTION, OR FOR SPECIAL, INDIRECT,
# CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF
# THE THEORY OF LIABILITY, AND EVEN IF BLUETOOTH SIG, ITS MEMBERS, OR THEIR
# AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# 
# This document is proprietary to Bluetooth SIG. This document may contain or
# cover subject matter that is intellectual property of Bluetooth SIG and its
# members. The furnishing of this document does not grant any license to any
# intellectual property of Bluetooth SIG or its members.
# 
# This document is subject to change without notice.
# 
# Copyright © 2020–2025 by Bluetooth SIG, Inc. The Bluetooth word mark and logos
# are owned by Bluetooth SIG, Inc. Other third-party brands and names are the
# property of their respective owners.

property:
  identifier: org.bluetooth.property.device_operating_temperature_statistical_values
  name: Device Operating Temperature Statistical Values
  group: org.bluetooth.property_group.device_operating_temperature
  characteristic: org.bluetooth.characteristic.temperature_statistics
  description: |-
    This property represents the average, standard deviation, minimum, and maximum operating temperatures and the data recording period as recorded by a temperature sensor. A value of 0 for the data recording period indicates that the period is the lifetime of the sensor.
    Example use case: These lifetime values for the operating temperature of an LED fixture can be used to predict the remaining lifetime of the fixture, which is strongly dependent on the operating temperature.
